# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnexiaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConnexiaApp
  pod 'Connexia', :git => 'https://github.com/nanhemaurya/Connexia.git', :tag => '1.0.0'

end
